#
#
# Makefile for brainfuck-interpreter
#
#	Abihshek Chakraborty
#
all: main

main: brainfuck-interpreter.cpp methods.cpp methods.h
	g++ -o brainfuck-interpreter brainfuck-interpreter.cpp methods.h methods.cpp

clean:
	rm -f *.o a.out main
